const groupNames = [
  "Friends Forever",
  "Family Ties",
  "Book Club",
  "Travel Buddies",
  "Fitness Freaks",
  "Movie Buffs",
  "Food Lovers",
  "Music Maniacs",
  "Adventure Seekers",
  "Weekend Warriors",
  "Coding Wizards",
  "Gaming Legends",
  "Photography Fans",
  "Sports Enthusiasts",
  "Pet Lovers",
  "Fashion Squad",
  "DIY Enthusiasts",
  "Tech Talk",
  "Study Group",
  "Work Buddies",
  "School Friends",
  "College Gang",
  "Neighbors United",
  "Party Planners",
  "Gardening Group",
  "Cooking Club",
  "Parenting Tips",
  "Science Geeks",
  "Art Lovers",
  "Spiritual Seekers",
  "Charity Workers",
  "Career Builders",
  "Investing Insights",
  "Health and Wellness",
  "Language Learners",
  "History Buffs",
  "Car Enthusiasts",
  "Dance Crew",
  "Karaoke Nights",
  "Wine Tasting",
];
export default groupNames;
